[build]
  publish = "public"
  command = ""

[[headers]]
  for = "/items.json"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
